### ISSUE TITLE
Make a sensible colorscheme

### ISSUE THREAD

**Issue by Z2h-A6n** [Z2h-A6n/greven-web#1]
The current colorscheme is crazy.

**Comment by Z2h-A6n** [comment]
A new colorscheme may also require a new choice of colors and options for the UMN header.

**Comment by JingnanC** [comment]
I chose a color scheme that corresponds to our UMN header color, and leave most background white.

**Comment by Z2h-A6n** [comment]
Merging this issue with #9 to form #20.

Closing.
