### ISSUE TITLE
Reorganize the publications page.

### ISSUE THREAD

**Issue by Z2h-A6n** [Z2h-A6n/greven-web#15]
Martin wants the Publications page organized in chronological order, with different css styling differentiating locally-produced papers from collaborative papers. I've done some of this already.
- [x] Differentiate the two publication types with css.
- [x] Put the publications in chronological order.
- [x] Add headings for each year.
- [x] Add some text explaining the colors and organizational scheme.
  - Add some buttons to choose what types of papers to show?

**Comment by Z2h-A6n** [comment]
I'm working on the buttons, but it may or may not be possible using html and css alone.
I think something along these lines may work:
https://stackoverflow.com/questions/21739528/change-css-style-on-button-click/21739608

**Comment by sajnahameed** [comment]
I'm working on putting the publications in chronological order.

**Comment by Z2h-A6n** [comment]
Adding buttons to selectively show and hide publications seems to be more trouble than it's worth. It can be added after the site launch if ever.

**Comment by Z2h-A6n** [comment]
Added some labels explaining the colors.

Closing.
