### ISSUE TITLE
Make the homepage look good.

### ISSUE THREAD

**Issue by Z2h-A6n** [Z2h-A6n/greven-web#9]
The easiest option would be to make good-looking banner image to put above (or below?) the nav bar.

Another nice (probably better) option is an automatic slideshow of a few good pictures, possibly with links to paragraphs on the Research page.

**Comment by Z2h-A6n** [comment]
Here's a simple option for a slideshow with HTML CSS and JS: [Link](https://css-tricks.com/snippets/jquery/simple-auto-playing-slideshow/)

It may also be possible to du it using just HTML5 and CSS3 using Transitions and/or animations: [Link](http://learn.shayhowe.com/advanced-html-css/transitions-animations/)

**Comment by JingnanC** [comment]
I changed the font type, size, alignment and line space on the website to enhance readability.

**Comment by Z2h-A6n** [comment]
I'm working on the banner/slideshow for the homepage, see issue #13.

We may want to make a small banner image or something to go in between the institutional headers and the nav bar on the other pages.

**Comment by Z2h-A6n** [comment]
Merging this issue with #1 to make #20.

Closing.
